name = "tmuxctl_test"
dir = "~/dev/bloom"

# selects the window to start in
select-window = "docker" 
# selects the pane to start in.
# must select a window  first, otherwise ignored
# first panel is 1 and so on...
# select-pane = 3

[[windows]]
  name="docker"
  dir="~/dev/bloom/dashboard-docker"
  # runs in the inital window pane before splitting
  scripts=[
    "touch test.text",
    "echo hello > test.text",
    "cd ../"
  ]
  # layout="tiled"
  # sync=true 

  [[windows.panes]]
    dir="~/dev/bloom/fb_scraper"
    # zoom=true
  [[windows.panes]]
    scripts=[
      "ls -larth",
      "echo coucou"
    ]
    # split horizontally and take full height
    split="-h -p 10" 
  [[windows.panes]]
    scripts=[
      "cat test.text"
    ]
    # split vertically and take full width
    split="-f -v"
  [[windows.panes]]
    # split horizontally spanning full height and take 20 cols
    split="-f -v -l 20"
  [[windows.panes]]
    # split vertically spanning full width and take 20 rows
    split="-f -h -l 50"

[[windows]]
  name="hub"
  dir="~/dev/bloom/bloom-hub"
  layout="main-horizontal"
#  sync=""

  [[windows.panes]]
 #   zoom=true
  [[windows.panes]]
    dir="~/dev/bloom/bloom-hub/apps/api"
  [[windows.panes]]
    dir="~/dev/bloom/bloom-hub/apps/app"

[[windows]]
  name="dashboard"
  dir="~/dev/bloom/dashboard"

  [[windows.panes]]
  [[windows.panes]]
    dir="~/dev/bloom/dashboard/scripts"

[[windows]]
  name="ssh"